services:
  - type: web
    name: code-mon-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: COMPILER_SERVICE_URL
        value: "http://your-ec2-public-ip:5001"  # Replace with your EC2 public IP
    healthCheckPath: /
    autoDeploy: true 